services:
  - type: web
    name: telegram-edit-guard-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: OWNER_NAME
        sync: false
      - key: START_IMAGE
        sync: false
      - key: SUPPORT_GROUP
        sync: false
      - key: SUPPORT_CHANNEL
        sync: false
      - key: WARNING_DELETE_DELAY
        value: 5
